version: '3.8'

services:
  mariadb:
    image: mariadb:11.3.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: devpassword
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - pregsfin_mariadb_data:/var/lib/mysql
    networks:
      - dev_network

volumes:
  pregsfin_mariadb_data:
    driver: local

networks:
  dev_network:
    driver: bridge
